/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacegrafica;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author arthur.fmoliveira
 */
public class JanelaConteudos extends javax.swing.JFrame {

    /**
     * Creates new form JanelaConteudos
     */
    public JanelaConteudos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        videoLilian = new javax.swing.JLabel();
        exerciciossaude = new javax.swing.JLabel();
        saudementalsaudecoletiva = new javax.swing.JLabel();
        saudepsicologia = new javax.swing.JLabel();
        politicasaude = new javax.swing.JLabel();
        forum = new javax.swing.JLabel();
        botaoVoltar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vídeos, Artigos e Fóruns");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Conteúdos");

        videoLilian.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        videoLilian.setText("Vamos falar sobre saúde mental? | Lilian Scheinkman");
        videoLilian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                videoLilianMouseClicked(evt);
            }
        });

        exerciciossaude.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        exerciciossaude.setText("Exercícios que Melhoram a Saúde Mental (Para que a Cura Interior Aconteça) - Dr. Cesar Psiquiatra");
        exerciciossaude.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exerciciossaudeMouseClicked(evt);
            }
        });

        saudementalsaudecoletiva.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        saudementalsaudecoletiva.setText("Saúde Mental e Saúde Coletiva - Artigo em PDF");
        saudementalsaudecoletiva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saudementalsaudecoletivaMouseClicked(evt);
            }
        });

        saudepsicologia.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        saudepsicologia.setText("Saúde Mental e Psicologia do Trabalho - Artigo Google Acadêmico");
        saudepsicologia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saudepsicologiaMouseClicked(evt);
            }
        });

        politicasaude.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        politicasaude.setText("Política de saúde mental no Brasil: uma visão histórica - Artigo Google Acadêmico");
        politicasaude.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                politicasaudeMouseClicked(evt);
            }
        });

        forum.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        forum.setText("Fórum Nacional de Atenção à Saúde Mental");
        forum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forumMouseClicked(evt);
            }
        });

        botaoVoltar2.setText("Voltar");
        botaoVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(254, 254, 254))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exerciciossaude, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saudementalsaudecoletiva)
                            .addComponent(saudepsicologia, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(politicasaude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(videoLilian)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(forum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoVoltar2)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(videoLilian)
                .addGap(18, 18, 18)
                .addComponent(exerciciossaude)
                .addGap(18, 18, 18)
                .addComponent(saudementalsaudecoletiva)
                .addGap(18, 18, 18)
                .addComponent(saudepsicologia)
                .addGap(18, 18, 18)
                .addComponent(politicasaude)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forum)
                    .addComponent(botaoVoltar2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void videoLilianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoLilianMouseClicked

    try {
    Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=UU-bd1lj3Kg"));
} catch (IOException | URISyntaxException e1) {
    e1.printStackTrace();
} return;

    }//GEN-LAST:event_videoLilianMouseClicked

    private void exerciciossaudeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exerciciossaudeMouseClicked
 try {
    Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=z5Qd8eCK4oc"));
} catch (IOException | URISyntaxException e1) {
    e1.printStackTrace();
} return;
        // TODO add your handling code here:
    }//GEN-LAST:event_exerciciossaudeMouseClicked

    private void saudementalsaudecoletivaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saudementalsaudecoletivaMouseClicked
try {
    Desktop.getDesktop().browse(new URI("https://d1wqtxts1xzle7.cloudfront.net/104157628/23-tratado-lancetti1-libre.pdf?1688990846=&response-content-disposition=inline%3B+filename%3DSaude_mental_e_saude_coletiva.pdf&Expires=1727395066&Signature=OZ7SbkQ5u026O8XSea1QqkoJ2p9xPTjdUjBmsyYceWm~ZMZmU39U9or9sGO8TPeHWKWZ5JBBmmqIy0kuXRDTjJsvgklDkW4z4ZN1vZIZiDXYA3ROT-dAbknVAOsGNbl~mEt4woZmzcTCKtnv2Ki~As5d8Fco8y4PdctMjoJnNTgMuouZBiblosRtiv8sBQmwLPILmsPqo784W4lNs0BdpbijKZHcllj5Gfel~Yd5hXAb8nWOuziB0hvRH2eY1DtJ~qHmSgkGKp-I1Itk4OCLvX9D8NZq4dSNrBuH6fKsvIrP4jtuCiAnf9bsTZfhrNW4RJlxkBwIO0WH7wAFXXmq2A__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA"));
} catch (IOException | URISyntaxException e1) {
    e1.printStackTrace();
} return;        // TODO add your handling code here:
    }//GEN-LAST:event_saudementalsaudecoletivaMouseClicked

    private void saudepsicologiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saudepsicologiaMouseClicked
try {
    Desktop.getDesktop().browse(new URI("https://www.scielo.br/j/spp/a/6gQBvK8LC7CM4Bzd5vNLH7H/"));
} catch (IOException | URISyntaxException e1) {
    e1.printStackTrace();
} return;        //         // TODO add your handling code here:
    }//GEN-LAST:event_saudepsicologiaMouseClicked

    private void politicasaudeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_politicasaudeMouseClicked
try {
    Desktop.getDesktop().browse(new URI("https://pesquisa.bvsalud.org/portal/resource/pt/lil-402113"));
} catch (IOException | URISyntaxException e1) {
    e1.printStackTrace();
} return;           // TODO add your handling code here:
    }//GEN-LAST:event_politicasaudeMouseClicked

    private void forumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forumMouseClicked
try {
    Desktop.getDesktop().browse(new URI("https://www.cnmp.mp.br/portal/institucional/comissoes/comissao-da-saude/saude-mental/forum-nacional-de-atencao-a-saude-mental"));
} catch (IOException | URISyntaxException e1) {
    e1.printStackTrace();
} return;          // TODO add your handling code here:
    }//GEN-LAST:event_forumMouseClicked

    private void botaoVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltar2ActionPerformed
    Janela2 Janela2 = new Janela2();
    dispose();
    Janela2.setVisible(true);
        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_botaoVoltar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaConteudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaConteudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaConteudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaConteudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaConteudos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar2;
    private javax.swing.JLabel exerciciossaude;
    private javax.swing.JLabel forum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel politicasaude;
    private javax.swing.JLabel saudementalsaudecoletiva;
    private javax.swing.JLabel saudepsicologia;
    private javax.swing.JLabel videoLilian;
    // End of variables declaration//GEN-END:variables
}
