/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacegrafica;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author llanc
 */
public class janelaMusicas extends javax.swing.JFrame {

    /**
     * Creates new form janelaMusicas
     */
    public janelaMusicas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        musicasAnsiedade = new javax.swing.JLabel();
        confiancaSola = new javax.swing.JButton();
        alugaseBarbara = new javax.swing.JButton();
        prometeAna = new javax.swing.JButton();
        pazIorc = new javax.swing.JButton();
        ameiTeVer = new javax.swing.JButton();
        linhaEquador = new javax.swing.JButton();
        stringVolta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seção de Músicas");

        musicasAnsiedade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        musicasAnsiedade.setText("Músicas para Alívio da Ansiedade");

        confiancaSola.setText("Confiança - Projeto Sola");
        confiancaSola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confiancaSolaActionPerformed(evt);
            }
        });

        alugaseBarbara.setText("Aluga-se Bárbara Dias");
        alugaseBarbara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alugaseBarbaraActionPerformed(evt);
            }
        });

        prometeAna.setText("Promete - Ana Vilela");
        prometeAna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prometeAnaActionPerformed(evt);
            }
        });

        pazIorc.setText("Nessa Paz eu Vou - Tiago Iorc");
        pazIorc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pazIorcActionPerformed(evt);
            }
        });

        ameiTeVer.setText("Amei Te Ver - Tiago Iorc");
        ameiTeVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ameiTeVerActionPerformed(evt);
            }
        });

        linhaEquador.setText("Linha do Equador - Melim");
        linhaEquador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linhaEquadorActionPerformed(evt);
            }
        });

        stringVolta.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        stringVolta.setText("Voltar");
        stringVolta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stringVoltaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confiancaSola)
                    .addComponent(prometeAna)
                    .addComponent(ameiTeVer))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linhaEquador)
                    .addComponent(pazIorc)
                    .addComponent(alugaseBarbara))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(musicasAnsiedade)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(stringVolta)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(musicasAnsiedade)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confiancaSola)
                    .addComponent(alugaseBarbara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prometeAna)
                    .addComponent(pazIorc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ameiTeVer)
                    .addComponent(linhaEquador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(stringVolta)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stringVoltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stringVoltaMouseClicked
    Janela2 Janela2 = new Janela2();
    dispose();
    Janela2.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_stringVoltaMouseClicked

    private void confiancaSolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confiancaSolaActionPerformed
    try {
    Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=65f5iCbWf1I"));
} catch (IOException | URISyntaxException e1) {
    e1.printStackTrace();
} return;
    }//GEN-LAST:event_confiancaSolaActionPerformed

    private void alugaseBarbaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alugaseBarbaraActionPerformed
 try {
    Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=oN1lbANZM5s"));
} catch (IOException | URISyntaxException e1) {
    e1.printStackTrace();
} return;        // TODO add your handling code here:
    }//GEN-LAST:event_alugaseBarbaraActionPerformed

    private void prometeAnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prometeAnaActionPerformed
try {
    Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=YbnEhG7tg2g"));
} catch (IOException | URISyntaxException e1) {
    e1.printStackTrace();
} return;                // TODO add your handling code here:
    }//GEN-LAST:event_prometeAnaActionPerformed

    private void pazIorcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pazIorcActionPerformed
try {
    Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=YVYVv1tTMGU"));
} catch (IOException | URISyntaxException e1) {
    e1.printStackTrace();
} return;                 // TODO add your handling code here:
    }//GEN-LAST:event_pazIorcActionPerformed

    private void ameiTeVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ameiTeVerActionPerformed
try {
    Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=W62-ZG9tPpI"));
} catch (IOException | URISyntaxException e1) {
    e1.printStackTrace();
} return;                // TODO add your handling code here:
    }//GEN-LAST:event_ameiTeVerActionPerformed

    private void linhaEquadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linhaEquadorActionPerformed
try {
    Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=6qjY6CkPLSE"));
} catch (IOException | URISyntaxException e1) {
    e1.printStackTrace();
} return;               // TODO add your handling code here:
    }//GEN-LAST:event_linhaEquadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janelaMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janelaMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janelaMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janelaMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janelaMusicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alugaseBarbara;
    private javax.swing.JButton ameiTeVer;
    private javax.swing.JButton confiancaSola;
    private javax.swing.JButton linhaEquador;
    private javax.swing.JLabel musicasAnsiedade;
    private javax.swing.JButton pazIorc;
    private javax.swing.JButton prometeAna;
    private javax.swing.JLabel stringVolta;
    // End of variables declaration//GEN-END:variables
}
