/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacegrafica;
import forms.ViewCurso;
import forms.ViewFeedback;
import forms.ViewProdutos;
import forms.ViewWebinars;

/**
 *
 * @author arthur.fmoliveira
 */
public class Janela2 extends javax.swing.JFrame {

    /**
     * Creates new form Janela2
     */
    public Janela2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        stringSistemadeEducaçãodeSaúdeMental = new javax.swing.JLabel();
        stringVideos = new javax.swing.JLabel();
        stringNovidades = new javax.swing.JLabel();
        stringSair = new javax.swing.JButton();
        stringMindfulness = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stringProdutos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton2.setText("jButton2");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        stringSistemadeEducaçãodeSaúdeMental.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stringSistemadeEducaçãodeSaúdeMental.setText("Sistema de Educação de Saúde Mental");

        stringVideos.setText("Para ver vídeos, artigos e fóruns, CLIQUE AQUI");
        stringVideos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stringVideosMouseClicked(evt);
            }
        });

        stringNovidades.setText("Para ver o que há de novo no momento, CLIQUE AQUI");
        stringNovidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stringNovidadesMouseClicked(evt);
            }
        });

        stringSair.setText("Sair");
        stringSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stringSairMouseClicked(evt);
            }
        });
        stringSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stringSairActionPerformed(evt);
            }
        });

        stringMindfulness.setText("Para ver técnicas de Mindfulness, CLIQUE AQUI");
        stringMindfulness.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stringMindfulnessMouseClicked(evt);
            }
        });

        jLabel1.setText("Para ouvir músicas tranquilas, CLIQUE AQUI");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Envie-nos um feedback!");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        stringProdutos.setText("Produtos");
        stringProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stringProdutosActionPerformed(evt);
            }
        });

        jButton1.setText("Cursos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Webinars");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stringSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stringMindfulness)
                                    .addComponent(stringNovidades)
                                    .addComponent(stringVideos)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(stringProdutos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addGap(41, 41, 41)
                                        .addComponent(jButton3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(stringSistemadeEducaçãodeSaúdeMental)))
                        .addGap(0, 57, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stringSistemadeEducaçãodeSaúdeMental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stringProdutos)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(33, 33, 33)
                .addComponent(stringVideos)
                .addGap(18, 18, 18)
                .addComponent(stringNovidades)
                .addGap(18, 18, 18)
                .addComponent(stringMindfulness)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stringSair, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stringNovidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stringNovidadesMouseClicked
    janelaNovidades janelaNovidades= new janelaNovidades();
    dispose();
    janelaNovidades.setVisible(true);
    }//GEN-LAST:event_stringNovidadesMouseClicked

    private void stringSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringSairActionPerformed
    Login Login = new Login();
    dispose();
    Login.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_stringSairActionPerformed

    private void stringVideosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stringVideosMouseClicked
    JanelaConteudos JanelaConteudos = new JanelaConteudos();
    dispose();
    JanelaConteudos.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_stringVideosMouseClicked

    private void stringSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stringSairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stringSairMouseClicked

    private void stringMindfulnessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stringMindfulnessMouseClicked
    janelaMindfulness janelaMindfulness = new janelaMindfulness();
    dispose();
    janelaMindfulness.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_stringMindfulnessMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    janelaMusicas janelaMusicas = new janelaMusicas();
    dispose();
    janelaMusicas.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    ViewFeedback janelaFeedback = new ViewFeedback();
    dispose();
    janelaFeedback.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void stringProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringProdutosActionPerformed
    ViewProdutos ViewProdutos = new ViewProdutos();
    dispose();
    ViewProdutos.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_stringProdutosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    ViewCurso ViewCurso = new ViewCurso();
    dispose();
    ViewCurso.setVisible(true);       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    ViewWebinars ViewWebinars = new ViewWebinars();
    dispose();
    ViewWebinars.setVisible(true);          
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel stringMindfulness;
    private javax.swing.JLabel stringNovidades;
    private javax.swing.JButton stringProdutos;
    private javax.swing.JButton stringSair;
    private javax.swing.JLabel stringSistemadeEducaçãodeSaúdeMental;
    private javax.swing.JLabel stringVideos;
    // End of variables declaration//GEN-END:variables
}
