/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacegrafica;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author llanc
 */
public class janelaNovidades extends javax.swing.JFrame {

    /**
     * Creates new form janelaNovidades
     */
    public janelaNovidades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stringNews = new javax.swing.JLabel();
        stringCNN = new javax.swing.JButton();
        stringG1 = new javax.swing.JButton();
        stringUSP = new javax.swing.JButton();
        stringVoltarNews = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Notícias");

        stringNews.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stringNews.setText("Notícias");

        stringCNN.setText("CNN Brasil");
        stringCNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stringCNNActionPerformed(evt);
            }
        });

        stringG1.setText("G1 Globo");
        stringG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stringG1ActionPerformed(evt);
            }
        });

        stringUSP.setText("Jornal da USP");
        stringUSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stringUSPActionPerformed(evt);
            }
        });

        stringVoltarNews.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        stringVoltarNews.setText("Voltar");
        stringVoltarNews.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stringVoltarNewsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(stringCNN)
                        .addGap(66, 66, 66)
                        .addComponent(stringG1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(stringUSP))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(stringNews)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(stringVoltarNews)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(stringNews)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stringCNN)
                    .addComponent(stringG1)
                    .addComponent(stringUSP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(stringVoltarNews)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stringCNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringCNNActionPerformed
try {
    Desktop.getDesktop().browse(new URI("https://www.cnnbrasil.com.br/tudo-sobre/saude-mental/"));
} catch (IOException | URISyntaxException e1) {
    e1.printStackTrace();
} return;        // TODO add your handling code here:
    }//GEN-LAST:event_stringCNNActionPerformed

    private void stringG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringG1ActionPerformed
try {
    Desktop.getDesktop().browse(new URI("https://g1.globo.com/saude/saude-mental/"));
} catch (IOException | URISyntaxException e1) {
    e1.printStackTrace();
} return;            // TODO add your handling code here:
    }//GEN-LAST:event_stringG1ActionPerformed

    private void stringUSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringUSPActionPerformed
try {
    Desktop.getDesktop().browse(new URI("https://jornal.usp.br/series/minuto-saude-mental/"));
} catch (IOException | URISyntaxException e1) {
    e1.printStackTrace();
} return;            // TODO add your handling code here:
    }//GEN-LAST:event_stringUSPActionPerformed

    private void stringVoltarNewsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stringVoltarNewsMouseClicked
    Janela2 Janela2 = new Janela2();
    dispose();
    Janela2.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_stringVoltarNewsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janelaNovidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janelaNovidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janelaNovidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janelaNovidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janelaNovidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton stringCNN;
    private javax.swing.JButton stringG1;
    private javax.swing.JLabel stringNews;
    private javax.swing.JButton stringUSP;
    private javax.swing.JLabel stringVoltarNews;
    // End of variables declaration//GEN-END:variables
}
